// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        id,
        Name,
        Email,
        password,
        createdAt,
        updatedAt
    )
VALUES ($1, $2, $3, $4,$5,$6) rETURNING id,
    name,
    createdAt,
    updatedAt
`

type CreateUserParams struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	Createdat time.Time
	Updatedat time.Time
}

type CreateUserRow struct {
	ID        uuid.UUID
	Name      string
	Createdat time.Time
	Updatedat time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Createdat,
		arg.Updatedat,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT name, email FROM users WHERE id = $1
`

type GetUserRow struct {
	Name  string
	Email string
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(&i.Name, &i.Email)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name password FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID       uuid.UUID
	Password string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = $2,
    email = $3,
    password = $4,
    updatedAt = $5
WHERE id = $1
RETURNING id, name, email, createdAt, updatedAt
`

type UpdateUserParams struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	Updatedat time.Time
}

type UpdateUserRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Createdat time.Time
	Updatedat time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Updatedat,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    name = $2,
    email = $3,
    updatedAt = $4
WHERE id = $1
RETURNING id, name, email, createdAt, updatedAt
`

type UpdateUserProfileParams struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Updatedat time.Time
}

type UpdateUserProfileRow struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Createdat time.Time
	Updatedat time.Time
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Updatedat,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
